name: DevOps CI/CD for GuitarShop ğŸ¸

on:
  push:
    branches:
      - main  # Tá»± Ä‘á»™ng cháº¡y khi báº¡n push lÃªn nhÃ¡nh main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1ï¸âƒ£ Láº¥y source code
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2ï¸âƒ£ ÄÄƒng nháº­p Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
         username: phuonglam2507
         password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            phuonglam2507/giutarshop:latest
            phuonglam2507/giutarshop:${{ github.sha }}
            
      - name: Verify
        run: echo "Image digest:" ${{ steps.docker_build.outputs.digest }}

      # 5ï¸âƒ£ Deploy lÃªn EC2 qua SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "ğŸš€ Deploying GuitarShop on EC2..."
            # KÃ©o image má»›i nháº¥t tá»« Docker Hub
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/guitarshop:latest
            # Dá»«ng container cÅ© (náº¿u cÃ³)
            docker stop guitarshop || true
            docker rm guitarshop || true
            # Cháº¡y container má»›i
            docker run -d --name guitarshop -p 80:3000 ${{ secrets.DOCKERHUB_USERNAME }}/guitarshop:latest
            echo "âœ… Deployment complete!"
